# Домашнее задание к лекции "Функции"

Вам нужно помочь секретарю автоматизировать работу. Для этого нужно написать программу, которая будет на основе хранимых данных исполнять пользовательские команды.

Исходные данные имеют следующую структуру:

1. перечень всех документов
```
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
```
2. перечень полок, на которых хранятся документы (если документ есть в documents, то он обязательно должен быть и в directories)
```
directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}
```

Общие требования к программе:
- код должен быть грамотно декомпозирован (каждая функция отвечает за свою конкретную задачу, дублирующийся функционал переиспользуется, а его код не повторяется);
- в коде отсутствуют глобальные переменные (за исключением **documents** и **directories**);
- пользовательский ввод обрабатывается в цикле **while** до тех пор, пока пользователь явно не завершит программу (вводом команды "**q**").

## Задание 1

### Пункт 1. Пользователь по команде "*p*" может узнать владельца документа по его номеру

Примеры работы:

1.

```
Введите команду:
p

Введите номер документа:
10006
```
Результат:  
`Владелец документа: Аристарх Павлов`

2.
```
Введите команду:
p

Введите номер документа:
12345
```
Результат:  
`Документ не найден в базе`

### Пункт 2. Пользователь по команде "*s*" может по номеру документа узнать на какой полке ион хранится

Примеры работы:

1.

```
Введите команду:
s

Введите номер документа:
10006
```
Результат:  
`Документ хранится на полке: 2`

2.
```
Введите команду:
s

Введите номер документа:
12345
```
Результат:  
`Документ не найден в базе`

### Пункт 3. Пользователь по команде "*l*" может увидеть полную информацию по всем документам

Пример работы:

```
Введите команду:
l
```

Результат:  
```
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

### Пункт 4. Пользователь по команде "*ads*" может добавить новую полку

Примеры работы:

1.

```
Введите команду:
ads

Введите номер полки:
10
```
Результат:  
`Полка добавлена. Текущий перечень полок: 1, 2, 3, 10.`

2.
```
Введите команду:
ads

Введите номер полки:
1
```
Результат:  
`Такая полка уже существует. Текущий перечень полок: 1, 2, 3.`

### Пункт 5. Пользователь по команде "*ds*" может удалить существующую полку из данных (только если она пустая)

Примеры работы:

1.

```
Введите команду:
ds

Введите номер полки:
3
```
Результат:  
`Полка удалена. Текущий перечень полок: 1, 2.`

2.
```
Введите команду:
ds

Введите номер полки:
1
```
Результат:  
`На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: 1, 2, 3.`

3.
```
Введите команду:
ds

Введите номер полки:
4
```
Результат:  
`Такой полки не существует. Текущий перечень полок: 1, 2, 3.`

 Решение. Код запускать по очереди.

In [ ]:
# Data
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}

In [ ]:
# 1.1 Поиск имени по номеру документа
def search_name(doc_no):
    """
    Ищет имя по номеру документа
    """
    # doc_no = str(input('Введите номер документа:'))
    for docs in documents:
        if docs['number'] == doc_no:
            return docs['name']
        else:
            None
    # return 'Документ не найден в базе'

In [ ]:
# 1.2 Поиск полки по номеру документа
def search_doc(doc_no):
    """
    Ищет полку документа по его номеру
    """    
    # doc_no = str(input('Введите номер документа:'))
    for k, v in directories.items():
        if doc_no in v:
            return k
        else:
            None
    # return

In [ ]:
# 1.3 Информация
def list_docs():
    """
    Показывет информацию по всем документам
    """
    list_docs = []
    for docs in documents:
        n = docs['number']
        t = docs['type']
        na = docs['name']
        s = search_doc(docs['number'])
        print(f'№: {n}, тип: {t}, владелец: {na}, полка хранения: {s}')
    return
    

In [ ]:
# 1.4 Добавление полки
def shelf_add(shelf_no):
    """
    Добавляет новую полку
    """
    if shelf_no not in directories.keys():
        return directories.setdefault(shelf_no, [])

In [ ]:
# 1.5 Удаление полки
def shelf_del(shelf_no):
    """
    Удаляет полку
    """
    if shelf_no in directories.keys():
        del(directories[shelf_no])

In [ ]:
# Проверка полок
def shelf_check(shelf_no):
    """
    Ищет наличие полки
    """
    if shelf_no in directories.keys():
        return True
    return False

In [ ]:
# Список полок
def shelf_list():
    """
    отображает текущий список полок
    """    
    sl = ', '.join(str(x) for x in list(directories.keys()))
    return sl

In [ ]:
# Содержимое полки
def shelf_contents(shelf_no):
    """
    Проверяет наличие документов на полке
    """
    return len(directories[shelf_no])

In [ ]:
# запрос данных о документе
def doc_ask():
    """
    Запрашивает данные о документе для операций создания, удаления и перемещения
    """
    doc_no = str(input('Введите номер документа:'))
    doc_type = str(input('Введите тип документа:'))
    doc_name = str(input('Введите владельца документа:'))
    shelf_no = str(input('Введите полку для хранения:'))
    doc_ask_dict = {'doc_no': doc_no, 'doc_type': doc_type, 'doc_name': doc_name, 'shelf_no': shelf_no}
    return doc_ask_dict

In [ ]:
# поиск документа по номеру
def doc_search(doc_no):
    """
    Ищет индекс документа в списке по номеру
    """
    for i, lines in enumerate(documents):
        if lines['number'] == doc_no:
            return i
    return False

In [ ]:
# Создание документа на полке
def doc_add(doc_ask_dict):
    """
    Создаёт новый документ и запись на соответствующей полке
    """
    directories[doc_ask_dict['shelf_no']].append(doc_ask_dict['doc_no']) # создаёт ID документа на полке
    documents.append({'type': doc_ask_dict['doc_type'], 'number': doc_ask_dict['doc_no'], 'name': doc_ask_dict['doc_name']}) # создаёт документ

In [ ]:
# Удаление документа
def doc_del(doc_no):
    """
    Удаляет документ и запись на соответствующей полке
    """
    documents.pop(doc_search(doc_no))
    return directories[str(search_doc(doc_no))].remove(doc_no)

In [ ]:
# Перемещение документа
def doc_move(shelf_no, doc_no):
    """
    Перекладываент документ на другую полку
    """
    directories[search_doc(doc_no)].remove(doc_no)
    return directories[shelf_no].append(doc_no)

In [ ]:
# Main
def main():
    while prog() != 'q':
        prog()
        continue
    return 'System shutdown'

In [ ]:
# Выбор программы
# можно было сообщения записать в функции, но мне показалось так менее удобно
# функции выполняют какие-то действия, а все сообщения прописаны в отдельном окне
# тем более, что так проще корректировать текст, если нужно, чтобы для разных команд
# текст немного отличался
def prog():
    cmd = input('Введите команду:')
    if cmd == 'q': # прекращение работы
        return 'q'

    elif cmd == 'p': # показать имя владельца по номеру
        doc_no = input('Введите номер документа:')
        if search_name(doc_no) == None:
            return print('Документ не наден в базе')
        else:
            return print(f'Владелец документа: {search_name(doc_no)}')

    elif cmd == 's': # показать полку хранения по номеру документа
        doc_no = input('Введите номер документа:')
        if search_doc(doc_no) == None:
            return print('Документ не наден в базе')
        else:
            return print(f'Документ хранится на полке: {search_doc(doc_no)}')

    elif cmd == 'l': # список всех документов
        return list_docs()

    elif cmd == 'ads': # добавление полки
        shelf_no = str(input('Введите номер полки:'))
        if shelf_check(shelf_no) is False:
            shelf_add(shelf_no)
            return print (f"Полка добавлена. Текущий перечень полок:", shelf_list())
        return print(f"Такая полка уже существует. Текущий перечень полок:", shelf_list())

    elif cmd == 'ds': # удаление полки
        shelf_no = str(input('Введите номер полки:'))
        if shelf_check(shelf_no) is False:
            return print (f"Такой полки не существует. Текущий перечень полок:", shelf_list())
        elif shelf_check(shelf_no) is True:
            if shelf_contents(shelf_no) != 0:
                return print (f"На полке есть документы. Текущий перечень полок:", shelf_list())
            elif shelf_contents(shelf_no) == 0:
                shelf_del(shelf_no)    
                return print(f"Полка удалена. Текущий перечень полок:", shelf_list())
        return print('Что-то странное')

    elif cmd == 'ad': # добавление документа
        doc_ask_dict = doc_ask()
        if shelf_check(doc_ask_dict['shelf_no']) is False:
            print('Такой полки не существует. Добавьте полку командой as.\nТекущий список документов:')
            return list_docs()
        elif shelf_check(doc_ask_dict['shelf_no']) is True:
            doc_add(doc_ask_dict)
            print('Документ добавлен. Текущий список документов:')
            return list_docs()   

    elif cmd == 'd': # удаление документа
        doc_no = str(input('Введите номер документа:'))
        if doc_search(doc_no) is False:
            print('Документ не найден в базе.\nТекущий список документов:')
            return list_docs()
        elif doc_search(doc_no) is not False:
            doc_del(doc_no)
            print('Документ удалён.\nТекущий список документов:')
            return list_docs()

    elif cmd == 'm': # перемещение документа
        doc_no = str(input('Введите номер документа:'))
        shelf_no = str(input('Введите номер полки:'))
        if doc_search(doc_no) is False:
            print('Документ не найден в базе.\nТекущий список документов:')
            return list_docs()
        elif shelf_check(shelf_no) is False:
            return print (f"Такой полки не существует. Текущий перечень полок:", shelf_list())
        elif doc_search(doc_no) is not False:
            doc_move(shelf_no, doc_no)
            print('Документ перемещён. Текущий список документов:')
            return list_docs()
            
    else:
        return print('Некорректная команда')

In [41]:
# Программа
# почему-то после выполнения команды, команду для выхода "q" иногда приходится вводить 2 раза. почему так разобраться не смог
main()

Документ не найден в базе.
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 3
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 1
Такой полки не существует. Текущий перечень полок: 1, 2, 3
Документ перемещён. Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 2
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 1


'System shutdown'

In [ ]:
# ТЕСТОВОЕ ПОЛЕ
# directories['2'].append('rer')
# directories['2'].remove('rer')
# documents.append({'type': 'mp', 'number': '111', 'name': 'Г H'})

# for i, lines in enumerate(documents):
#     if lines['number'] == '10006':
#         print(i)

## Задание 2 (необязательное)

Вам необходимо дополнить программу из задания 1 более продвинутыми командами.

### Пункт 1. Пользователь по команде "*ad*" может добавить новый документ в данные

Примеры работы:

1.

```
Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
3
```
Результат:  
```
Документ добавлен. Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№: 42, тип: multipassport, владелец: R2D2, полка хранения: 3
```

2.
```
Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
4
```
Результат:  
```
Такой полки не существует. Добавьте полку командой as. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

### Пункт 2. Пользователь по команде "*d*" может удалить документ из данных

Примеры работы:

1.

```
Введите команду:
d

Введите номер документа:
10006
```
Результат:  
```
Документ удален. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
```

2.
```
Введите команду:
d

Введите номер документа:
123456
```
Результат:  
```
Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

### Пункт 3. Пользователь по команде "*m*" может переместить документ с полки на полку

Примеры работы:

1.

```
Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
3
```
Результат:  
```
Документ перемещен. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 3
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

2.
```
Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
10
```
Результат:  
`Такой полки не существует. Текущий перечень полок: 1, 2, 3.`

3.
```
Введите команду:
m

Введите номер документа:
42
Введите номер полки:
2
```
Результат:  
```
Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

#### ПРИМЕЧАНИЕ
Домашнее задание сдается ссылкой [Google Colab](https://colab.research.google.com/).
Не сможем проверить или помочь, если вы пришлете:
- файлы;
- архивы;
- скриншоты кода.

Все обсуждения и консультации по выполнению домашнего задания ведутся только на соответствующем канале в slack.

##### Как правильно задавать вопросы аспирантам, преподавателям и коллегам
Прежде чем задать вопрос, попробуйте найти ответ в интернете. Навык самостоятельного поиска информации — один из важнейших. Каждый практикующий специалист любого уровня делает это ежедневно.

Сформулируйте вопрос по алгоритму:  
1) Что я делаю?  
2) Какого результата я ожидаю?  
3) Как фактический результат отличается от ожидаемого?  
4) Что я уже попробовал сделать, чтобы исправить проблему?  

По возможности прикрепите к вопросу скриншоты либо ссылки на код. Не выкладывайте все решение, оставляйте только проблемный и воспроизводимый участок кода.